-- Create BUSINESSES table
CREATE TABLE IF NOT EXISTS BUSINESSES (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  email VARCHAR(255),
  currency VARCHAR(10) DEFAULT 'USD',
  timezone VARCHAR(50) DEFAULT 'UTC',
  whatsapp_token TEXT,
  razorpay_secret TEXT,
  plan VARCHAR(50) DEFAULT 'free',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create USERS table
CREATE TABLE IF NOT EXISTS USERS (
  id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  business_id UUID NOT NULL REFERENCES BUSINESSES(id) ON DELETE CASCADE,
  role VARCHAR(50) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create CUSTOMERS table
CREATE TABLE IF NOT EXISTS CUSTOMERS (
  id UUID PRIMARY KEY,
  business_id UUID NOT NULL REFERENCES BUSINESSES(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(20),
  address TEXT,
  city VARCHAR(100),
  state VARCHAR(100),
  zip VARCHAR(20),
  country VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create INVOICES table
CREATE TABLE IF NOT EXISTS INVOICES (
  id UUID PRIMARY KEY,
  business_id UUID NOT NULL REFERENCES BUSINESSES(id) ON DELETE CASCADE,
  customer_id UUID NOT NULL REFERENCES CUSTOMERS(id) ON DELETE CASCADE,
  amount DECIMAL(12, 2) NOT NULL,
  status VARCHAR(50) DEFAULT 'pending',
  due_date DATE,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create PAYMENTS table
CREATE TABLE IF NOT EXISTS PAYMENTS (
  id UUID PRIMARY KEY,
  invoice_id UUID NOT NULL REFERENCES INVOICES(id) ON DELETE CASCADE,
  amount DECIMAL(12, 2) NOT NULL,
  payment_method VARCHAR(50),
  status VARCHAR(50) DEFAULT 'success',
  transaction_id VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create REMINDER_LOGS table
CREATE TABLE IF NOT EXISTS REMINDER_LOGS (
  id UUID PRIMARY KEY,
  invoice_id UUID NOT NULL REFERENCES INVOICES(id) ON DELETE CASCADE,
  channel VARCHAR(50),
  sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(50) DEFAULT 'sent'
);

-- Create AUDIT_LOGS table
CREATE TABLE IF NOT EXISTS AUDIT_LOGS (
  id UUID PRIMARY KEY,
  business_id UUID NOT NULL REFERENCES BUSINESSES(id) ON DELETE CASCADE,
  user_id UUID REFERENCES USERS(id) ON DELETE SET NULL,
  action VARCHAR(255),
  details TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create NOTIFICATION_TEMPLATES table
CREATE TABLE IF NOT EXISTS NOTIFICATION_TEMPLATES (
  id UUID PRIMARY KEY,
  business_id UUID NOT NULL REFERENCES BUSINESSES(id) ON DELETE CASCADE,
  name VARCHAR(255),
  channel VARCHAR(50),
  template TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_users_business_id ON USERS(business_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON USERS(email);
CREATE INDEX IF NOT EXISTS idx_customers_business_id ON CUSTOMERS(business_id);
CREATE INDEX IF NOT EXISTS idx_invoices_business_id ON INVOICES(business_id);
CREATE INDEX IF NOT EXISTS idx_invoices_customer_id ON INVOICES(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON INVOICES(status);
CREATE INDEX IF NOT EXISTS idx_payments_invoice_id ON PAYMENTS(invoice_id);
CREATE INDEX IF NOT EXISTS idx_reminder_logs_invoice_id ON REMINDER_LOGS(invoice_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_business_id ON AUDIT_LOGS(business_id);
